server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localbusiness?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@1008
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@example.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: prod

razorpay:
  key:
    id: rzp_test_your_test_key_id
    secret: your_test_secret_key

# Test profile configuration
---
spring:
  config:
    activate:
      on-profile: test
  mail:
    host: localhost
    port: 1025
    username: test@example.com
    password: test-password 