server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localbusiness?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@1008
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@example.com
    password: test-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: prod

stripe:
  secret-key: sk_test_51XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXbUfH9dQXXj6LrnMkPqFzXP7g0
  publishable-key: pk_test_51XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXbUfH9dQXXj6LrnMkPqFzXP7g0
  webhook-secret: whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Test profile configuration
---
spring:
  config:
    activate:
      on-profile: test
  mail:
    host: localhost
    port: 1025
    username: test@example.com
    password: test-password 